---
platform: linux

image_resource:
  type: registry-image
  source: { repository: gstack/gk-ops }

inputs:
  - name: artifact
  - name: gk-automation

outputs:
  - name: artifact-gzipped

params:
  ARTIFACT_FILE:

run:
  path: gk-automation/tasks/gzip-file.sh
