---
platform: linux

image_resource:
  type: registry-image
  source: { repository: gstack/gk-ops }

inputs:
  - name: artifact-version # type: github-release or hashicorp-release,
                           #       or anything providing a 'version' file
  - name: repo             # type: git
  - name: gk-automation    # type: git

outputs:
  - name: repo-branched    # type: git
  - name: branch-info      # type: keyvalue, files: 'branch-name'

params:
  BASE_BRANCH:
  BRANCH_NAME_TEMPLATE:
  GITHUB_PRIVATE_KEY:

run:
  path: gk-automation/tasks/git/checkout-branch.sh
