---
platform: linux

image_resource:
  type: registry-image
  source: { repository: gstack/gk-ops }

inputs:
  - name: repo          # type: git
  - name: gk-automation # type: git
  - name: commit-info   # type: keyvalue, with a 'commit-message' file
    optional: true

outputs:
  - name: repo-committed

params:
  GIT_COMMIT_NAME:
  GIT_COMMIT_EMAIL:

  GIT_COMMIT_MESSAGE:
  # Optional
  # One of 'commit-info' resource of 'GIT_COMMIT_MESSAGE' param must be
  # specified. Takes precedence over the 'commit-info' resource.

run:
  path: gk-automation/tasks/git/commit.sh
