---
platform: linux

image_resource:
  type: registry-image
  source: { repository: gstack/gk-ops }

inputs:
  - name: branch-info   # type: keyvalue, files: 'branch-name' and 'base-branch'
    optional: true
  - name: repo          # type: git
  - name: gk-automation # type: git

outputs:
  - name: repo-pushed   # type: git

params:
  GIT_URI:
  GITHUB_PRIVATE_KEY:

  BRANCH_NAME:
  # Optional
  # One of 'branch-info/branch-name' file or 'BRANCH_NAME' param must be specified.
  # Takes precedence over the 'branch-info' resource.

  BASE_BRANCH:
  # Optional
  # One of 'branch-info/base-branch' file or 'BASE_BRANCH' param must be specified.
  # Takes precedence over the 'branch-info' resource.

run:
  path: gk-automation/tasks/git/push-to-branch.sh
