---
platform: linux

image_resource:
  type: registry-image
  source: { repository: gstack/gk-ops }

inputs:
  - name: branch-info   # type: keyvalue, with a 'branch-name' file
    optional: true
  - name: repo          # type: git
  - name: gk-automation # type: git

params:
  GIT_URI:
  GITHUB_PRIVATE_KEY:

  BRANCH_NAME:
  # Optional
  # One of 'branch-info' resource of 'BRANCH_NAME' param must be specified.
  # Takes precedence over the 'branch-info' resource.

run:
  path: gk-automation/tasks/git/push-to-branch.sh
