---
pipeline_name: gk-ops-image
team_name: gk-plat-ops

git_user_name: Gstack Concourse Ninja

git_uri: git@github.com:gstackio/gk-automation.git
git_branch: master

image_version_git_uri: git@github.com:gstackio/gk-pipelines-compass.git
image_version_git_branch: master

dockerhub_username: gkconcourseninja
docker_registry_repo: harbor.ci.gstack.io/gstack/gk-ops
docker_registry_username: admin
