---
pipeline_name: gk-ops-image
team_name: gk-plat-ops

git_user_name: Gstack Concourse Ninja

git_uri: git@github.com:gstackio/gk-automation.git
git_branch: master

image_version_git_uri: git@github.com:gstackio/gk-pipelines-compass.git
image_version_git_branch: master

dockerhub_repo: gstack/gk-ops
dockerhub_username: gkconcourseninja
