---
platform: linux

image_resource:
  type: registry-image
  source: { repository: gstack/gk-ops }

inputs:
  - name: bosh-io-release # type: bosh-io-release
  - name: repo            # type: git
  - name: gk-automation   # type: git

outputs:
  - name: repo-bumped     # type: git
  - name: commit-info     # type: keyvalue, file: 'commit-message'
  - name: bump-info       # type: keyvalue, file: 'artifact-version'

params:
  RELEASE_NAME:
  MANIFEST_PATH:

run:
  path: gk-automation/tasks/boshrelease/depl-manifest-release-bump.sh
